spring:
  datasource:
    name: libraryDB
    username : sa
    password:
    url:
      jdbc:h2:file:./src/main/resources/database/libraryDB
    driver-class-name: org.h2.Driver


  jpa:
    database-platform : org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
       ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

  sql:
    init:
      data-locations: classpath:data/categories.sql








  mail:
    protocol: smtp
    host : smtp.gmail.com
    username: noreply.library.test@gmail.com
    password: password1Test
    port: 587
    properties:
     mail:
      smtp:
       auth: true
       starttls:
        enable: true
    test-connection: false

